import React,{useEffect,useMemo,useRef,useState}from"react";
import { exportVideoClip, renderProject } from "./mediaEngine";
import{createRoot}from"react-dom/client";
import{Play,Pause,Square,Upload,Undo2,Redo2,Scissors,Trash2,Sparkles,Layers,Download,Maximize,Plus,Eye,Lock,Music,Type,Sticker,SlidersHorizontal,Film,AudioLines,Blend,KeyRound,ScanLine,Move3d,RotateCcw,Save,Settings,Check,Search,Mic,Camera,Grid3X3,Cloud,Users,History,Tag,Zap,Volume2,Palette,Smile,Clapperboard,ShieldCheck}from"lucide-react";
import"./styles.css";

type Kind="video"|"image"|"audio"|"text"|"vfx"|"shape";
type Layer={id:string;name:string;kind:Kind;src?:string;start:number;duration:number;visible:boolean;locked:boolean;x:number;y:number;scale:number;rotation:number;opacity:number;blend:string;speed:number;effect?:string;color?:string;keyframes:Record<string,{time:number;value:number}[]>;mask?:{type:"none"|"circle"|"rectangle"|"line"|"split"|"custom";feather:number};crop?:{x:number;y:number;width:number;height:number};transition?:{type:"none"|"fade"|"dissolve"|"wipe"|"zoom";duration:number};colorAdjust?:{brightness:number;contrast:number;saturation:number;blur:number}};
type Project={name:string;width:number;height:number;fps:number;duration:number;layers:Layer[];settings:Record<string,any>};

const uid=()=>crypto.randomUUID();
const features=[
["Core Timeline & Canvas",1,"Multi-track timeline","core"],["Core Timeline & Canvas",2,"Precision trim + split with waveform","core"],["Core Timeline & Canvas",3,"Ripple / Roll / Slip editing","core"],["Core Timeline & Canvas",4,"Canvas ratios 9:16 / 16:9 / 1:1 / 4:5 / custom","core"],["Core Timeline & Canvas",5,"Magnetic snapping","core"],["Core Timeline & Canvas",6,"Keyframe engine","core"],["Core Timeline & Canvas",7,"Picture-in-picture","core"],["Core Timeline & Canvas",8,"Speed ramping + pitch preservation","core"],["Core Timeline & Canvas",9,"Reverse","core"],["Core Timeline & Canvas",10,"Freeze frame","core"],["Core Timeline & Canvas",11,"Non-destructive undo / redo","core"],["Core Timeline & Canvas",12,"Autosave","core"],["Core Timeline & Canvas",13,"Gridlines / safe zones","core"],["Core Timeline & Canvas",14,"Batch clip splitting","core"],["Core Timeline & Canvas",15,"Media replacement","core"],
["AI & Smart Automation",16,"AI background removal","smart"],["AI & Smart Automation",17,"Smart auto-captions + word animation","smart"],["AI & Smart Automation",18,"Text-based editing","smart"],["AI & Smart Automation",19,"AI noise suppression","smart"],["AI & Smart Automation",20,"Auto ducking","smart"],["AI & Smart Automation",21,"AI object tracking","smart"],["AI & Smart Automation",22,"AI voice transformer / pitch modifier","smart"],["AI & Smart Automation",23,"AI super-resolution","smart"],["AI & Smart Automation",24,"Beat detection sync","smart"],["AI & Smart Automation",25,"Generative fill / expansion","smart"],["AI & Smart Automation",26,"Face auto-centering","smart"],["AI & Smart Automation",27,"AI voice-over generator","smart"],["AI & Smart Automation",28,"Lip-sync matcher","smart"],["AI & Smart Automation",29,"Auto-silence removal","smart"],["AI & Smart Automation",30,"Eye-contact correction","smart"],
["Color / Lighting / Optics",31,"Color wheels","color"],["Color / Lighting / Optics",32,"HSL curves","color"],["Color / Lighting / Optics",33,"3D LUT","color"],["Color / Lighting / Optics",34,"Selective brushes","color"],["Color / Lighting / Optics",35,"Auto color match","color"],["Color / Lighting / Optics",36,"Vignette / grain","color"],["Color / Lighting / Optics",37,"Chroma key","color"],["Color / Lighting / Optics",38,"HDR / RAW pipeline","color"],["Color / Lighting / Optics",39,"Skin tone protection","color"],["Color / Lighting / Optics",40,"Dehaze / clarity","color"],["Color / Lighting / Optics",41,"Lens distortion correction","color"],["Color / Lighting / Optics",42,"Light flare / leak overlays","color"],["Color / Lighting / Optics",43,"B&W gradient mapping","color"],["Color / Lighting / Optics",44,"White-balance picker","color"],["Color / Lighting / Optics",45,"Split toning","color"],
["Audio",46,"Multiband EQ","audio"],["Audio",47,"Royalty-free asset library","audio"],["Audio",48,"Fade curves","audio"],["Audio",49,"Normalization","audio"],["Audio",50,"Stereo panning","audio"],["Audio",51,"Voice-over recorder","audio"],["Audio",52,"Detach / extract audio","audio"],["Audio",53,"Reverb / echo","audio"],["Audio",54,"SFX markers","audio"],["Audio",55,"Vocal extractor","audio"],["Audio",56,"Pitch shift without speed change","audio"],["Audio",57,"Compressor","audio"],["Audio",58,"Multitrack mixer","audio"],["Audio",59,"Sound visualizer","audio"],["Audio",60,"Copyright checker","audio"],
["Typography / Graphics / VFX",61,"Animated text templates","graphics"],["Typography / Graphics / VFX",62,"Custom fonts","graphics"],["Typography / Graphics / VFX",63,"Text on path","graphics"],["Typography / Graphics / VFX",64,"3D text","graphics"],["Typography / Graphics / VFX",65,"Transitions","graphics"],["Typography / Graphics / VFX",66,"Blending modes","graphics"],["Typography / Graphics / VFX",67,"Masking / draw masks","graphics"],["Typography / Graphics / VFX",68,"Motion blur","graphics"],["Typography / Graphics / VFX",69,"Sticker / GIF integration","graphics"],["Typography / Graphics / VFX",70,"Censorship / blur with tracking","graphics"],["Typography / Graphics / VFX",71,"Outro / intro builder","graphics"],["Typography / Graphics / VFX",72,"Watermark","graphics"],["Typography / Graphics / VFX",73,"Green-screen asset library","graphics"],["Typography / Graphics / VFX",74,"Speed lines / manga FX","graphics"],["Typography / Graphics / VFX",75,"Animated lower thirds","graphics"],
["Portrait / Retouch",76,"AI blemish / object spot healing","portrait"],["Portrait / Retouch",77,"Face reshaping / contouring","portrait"],["Portrait / Retouch",78,"Teeth whitening / eye brightening","portrait"],["Portrait / Retouch",79,"Body proportion","portrait"],["Portrait / Retouch",80,"Makeup overlays","portrait"],["Portrait / Retouch",81,"Skin smoothing","portrait"],["Portrait / Retouch",82,"Portrait bokeh","portrait"],["Portrait / Retouch",83,"Hair color","portrait"],["Portrait / Retouch",84,"Red-eye correction","portrait"],["Portrait / Retouch",85,"3D relighting","portrait"],
["Export / Management / Collaboration",86,"MP4 / MOV / GIF / WebM / ProRes","export"],["Export / Management / Collaboration",87,"Custom resolution / FPS 720p–4K 24/30/60","export"],["Export / Management / Collaboration",88,"VBR bitrate","export"],["Export / Management / Collaboration",89,"GIF generator","export"],["Export / Management / Collaboration",90,"Direct social publishing","export"],["Export / Management / Collaboration",91,"Multi-ratio export","export"],["Export / Management / Collaboration",92,"Project templates","export"],["Export / Management / Collaboration",93,"Cloud backup / cross-device sync","export"],["Export / Management / Collaboration",94,"Shared workspace / comments","export"],["Export / Management / Collaboration",95,"Version history / branching","export"],["Export / Management / Collaboration",96,"Asset tagging","export"],["Export / Management / Collaboration",97,"Background rendering","export"],["Export / Management / Collaboration",98,"Hardware acceleration","export"],["Export / Management / Collaboration",99,"Preset export profiles","export"],["Export / Management / Collaboration",100,"In-app camera + teleprompter / live filters","export"]
] as const;

const modules=[...new Set(features.map(x=>x[0]))];
const capcutTools=[
  ["Edit",Scissors,"Edit"],["Audio",Music,"Audio"],["Text",Type,"Text"],["Stickers",Sticker,"Stickers"],["Overlay",Layers,"Picture-in-picture"],["Effects",Sparkles,"Effects"],["Transitions",Blend,"Transitions"],["Filters",Palette,"Filters"],["Adjust",SlidersHorizontal,"Color / Lighting / Optics"],["Speed",Zap,"Speed ramping + pitch preservation"],["Animation",Move3d,"Keyframe engine"],["Mask",ScanLine,"Masking / draw masks"],["Chroma",Film,"Chroma key"],["Captions",Mic,"Smart auto-captions + word animation"],["Canvas",Grid3X3,"Canvas ratios 9:16 / 16:9 / 1:1 / 4:5 / custom"],["Voiceover",Mic,"Voice-over recorder"],["Retouch",Smile,"Portrait / Retouch"],["VFX",Zap,"Fire"],["Background",Cloud,"AI background removal"],["Export",Download,"Export / Management / Collaboration"]
] as const;
const moduleIcon:any={"Core Timeline & Canvas":Layers,"AI & Smart Automation":Sparkles,"Color / Lighting / Optics":Palette,"Audio":Volume2,"Typography / Graphics / VFX":Type,"Portrait / Retouch":Smile,"Export / Management / Collaboration":Settings};
const vfx=["Fire","Fireball","Fire in Hand","Fire Trail","Fire Weapon","Fire Explosion","Embers","Sparks","Lightning","Electric Hand","Lightning Beam","Energy Ball","Energy Beam","Energy Blast","Energy Shield","Smoke","Fog","Dust","Magic Portal","Fire Portal","Lightning Portal","Magic Circle","Shockwave","Glow","Motion Trail","Camera Shake","Speed Lines","Manga Flash"];
const fresh=():Project=>({name:"New Project",width:1080,height:1920,fps:30,duration:10,layers:[],settings:{snap:true,grid:false,safe:false,autosave:true,bitrate:12,format:"WebM",quality:"1080p",captionStyle:"Bold"}});

function App(){
 const[p,setP]=useState(fresh);const[selected,setSelected]=useState<string|null>(null);const[screen,setScreen]=useState<"home"|"editor">("home");const[splash,setSplash]=useState(true);const[t,setT]=useState(0);const[playing,setPlaying]=useState(false);const[tab,setTab]=useState("Edit");const[history,setHistory]=useState<Project[]>([]);const[future,setFuture]=useState<Project[]>([]);const[markers,setMarkers]=useState<number[]>([]);const[notice,setNotice]=useState("Ready");const[search,setSearch]=useState("");const[feature,setFeature]=useState<number|null>(null);const canvas=useRef<HTMLCanvasElement>(null);const vids=useRef<Record<string,HTMLVideoElement|null>>({});
 const sel=p.layers.find(x=>x.id===selected);
 const commit=(n:Project)=>{setHistory(h=>[...h,p].slice(-50));setFuture([]);setP(n)};
 useEffect(()=>{const a=setTimeout(()=>setSplash(false),1200);return()=>clearTimeout(a)},[]);
 useEffect(()=>{if(!p.settings.autosave)return;const a=setTimeout(()=>localStorage.setItem("divedit-project",JSON.stringify(p)),800);return()=>clearTimeout(a)},[p]);
 useEffect(()=>{if(!playing)return;let f:number;const tick=()=>{setT(x=>{const n=x+1/p.fps;if(n>=p.duration){setPlaying(false);return 0}return n});f=requestAnimationFrame(tick)};f=requestAnimationFrame(tick);return()=>cancelAnimationFrame(f)},[playing,p.fps,p.duration]);
 useEffect(()=>draw(),[p,t,selected]);
 const ratio=()=>p.width/p.height;
 function draw(){const c=canvas.current;if(!c)return;const g=c.getContext("2d");if(!g)return;c.width=540;c.height=Math.round(540/ratio());g.clearRect(0,0,c.width,c.height);g.fillStyle="#080808";g.fillRect(0,0,c.width,c.height);const s=Math.min(c.width/p.width,c.height/p.height);g.save();g.translate((c.width-p.width*s)/2,(c.height-p.height*s)/2);g.scale(s,s);
 p.layers.filter(l=>l.visible&&t>=l.start&&t<=l.start+l.duration).forEach(l=>{const adj=l.colorAdjust||{brightness:0,contrast:1,saturation:1,blur:0};g.save();g.globalAlpha=l.opacity;g.globalCompositeOperation=l.blend==="Add"?"lighter":l.blend==="Screen"?"screen":l.blend==="Multiply"?"multiply":"source-over";g.translate(l.x,l.y);g.rotate(l.rotation*Math.PI/180);g.scale(l.scale,l.scale);
 if(l.kind!=="audio" && adj && (adj.brightness||adj.contrast!==1||adj.saturation!==1||adj.blur)){g.filter=`brightness(${100+adj.brightness}%) contrast(${adj.contrast*100}%) saturate(${adj.saturation*100}%) blur(${adj.blur}px)`}      if(l.kind==="text"){g.fillStyle=l.color||"#fff";g.font="900 86px Arial";g.textAlign="center";g.shadowBlur=16;g.shadowColor=l.color||"#fff";g.fillText(l.name,0,0)}
 else if(l.kind==="vfx")paintVfx(g,l.effect||"Fire",t,l.color);
 else {const v=vids.current[l.id];if(v&&v.readyState>=2){g.drawImage(v,-p.width/2,-p.height/2,p.width,p.height)}else{g.fillStyle="#202020";g.fillRect(-p.width/2,-p.height/2,p.width,p.height);g.fillStyle="#aaa";g.font="bold 42px Arial";g.textAlign="center";g.fillText(l.name,0,0)}}g.restore()});g.restore();
 if(p.settings.grid){g.strokeStyle="rgba(255,255,255,.18)";g.lineWidth=1;for(let i=1;i<3;i++){g.beginPath();g.moveTo(c.width*i/3,0);g.lineTo(c.width*i/3,c.height);g.stroke();g.beginPath();g.moveTo(0,c.height*i/3);g.lineTo(c.width,c.height*i/3);g.stroke()}}
 if(p.settings.safe){g.strokeStyle="rgba(255,255,255,.5)";g.strokeRect(c.width*.08,c.height*.08,c.width*.84,c.height*.84)}
 }
 function paintVfx(g:CanvasRenderingContext2D,e:string,time:number,color?:string){const q=.8+.2*Math.sin(time*9);g.save();if(e.includes("Lightning")||e.includes("Electric")){g.strokeStyle=color||"#8de8ff";g.lineWidth=15;g.shadowBlur=35;g.shadowColor=g.strokeStyle;g.beginPath();g.moveTo(-240,0);for(let i=1;i<9;i++)g.lineTo(-240+i*60,(i%2?90:-90)*q);g.lineTo(240,0);g.stroke()}else if(e.includes("Portal")||e.includes("Circle")){g.strokeStyle=color||"#8de8ff";g.lineWidth=11;g.shadowBlur=30;g.shadowColor=g.strokeStyle;for(let r=230;r>35;r-=38){g.beginPath();g.arc(0,0,r,0,Math.PI*2);g.stroke()}}else if(e.includes("Smoke")||e.includes("Fog")||e.includes("Dust")){g.fillStyle="rgba(190,190,190,.22)";for(let i=0;i<12;i++){const a=time*1.7+i;g.beginPath();g.arc(Math.cos(a)*180,Math.sin(a*1.4)*150,35+(i%4)*18,0,Math.PI*2);g.fill()}}else{const grd=g.createRadialGradient(0,0,8,0,0,250);grd.addColorStop(0,"#fff");grd.addColorStop(.18,color||"#ffe56e");grd.addColorStop(.5,"#ff6420");grd.addColorStop(1,"transparent");g.fillStyle=grd;g.shadowBlur=55;g.shadowColor=color||"#ff5a16";g.beginPath();g.arc(0,0,(e.includes("Explosion")?280:220)*q,0,Math.PI*2);g.fill()}g.restore()}
 function add(kind:Kind,name:string,src?:string,effect?:string){const l:Layer={id:uid(),name,kind,src,start:t,duration:3,visible:true,locked:false,x:p.width/2,y:p.height/2,scale:1,rotation:0,opacity:1,blend:kind==="vfx"?"Add":"Normal",speed:1,effect,keyframes:{},mask:{type:"none",feather:0},crop:{x:0,y:0,width:1,height:1}};commit({...p,layers:[...p.layers,l],duration:Math.max(p.duration,t+3)});setSelected(l.id)}
 function importFiles(e:React.ChangeEvent<HTMLInputElement>){Array.from(e.target.files||[]).forEach(f=>add(f.type.startsWith("audio")?"audio":f.type.startsWith("image")?"image":"video",f.name,URL.createObjectURL(f)));e.target.value="";setScreen("editor");setNotice("Media imported")}
 function split(){if(!sel){setNotice("Select a clip first");return}const a=t-sel.start;if(a<=.05||a>=sel.duration){setNotice("Move the playhead inside the clip");return}commit({...p,layers:p.layers.flatMap(l=>l.id===sel.id?[{...l,duration:a},{...l,id:uid(),start:t,duration:l.duration-a}]:[l])});setNotice("Clip split")}
 function undo(){if(!history.length)return;setFuture(f=>[p,...f]);setP(history.at(-1)!);setHistory(h=>h.slice(0,-1))}
 function redo(){if(!future.length)return;setHistory(h=>[...h,p]);setP(future[0]);setFuture(f=>f.slice(1))}
 function save(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:"application/json"}));a.download="div-edit-project.json";a.click();setNotice("Project saved")}
 function exportVideo(){
  const formats:any={"720p":[720,1280],"1080p":[1080,1920],"1440p":[1440,2560],"4K":[2160,3840]};
  const [w,h]=formats[p.settings.quality]||formats["1080p"];
  setNotice("Preparing multi-track render…");
  renderProject({
    layers:p.layers,duration:p.duration,fps:p.fps,width:w,height:h,bitrate:p.settings.bitrate,
    drawLayer:(g,l,time,m)=>{
      const scale=Math.min(w/p.width,h/p.height);
      const local=Math.max(0,time-l.start), progress=Math.min(1,Math.max(0,local/Math.max(.001,l.duration)));
      const interp=(prop:string,base:number)=>{const k=(l.keyframes&&l.keyframes[prop])||[]; if(!k.length)return base; const a=[...k].sort((x,y)=>x.time-y.time); if(time<=a[0].time)return a[0].value; if(time>=a[a.length-1].time)return a[a.length-1].value; for(let i=0;i<a.length-1;i++){if(time>=a[i].time&&time<=a[i+1].time){const q=(time-a[i].time)/Math.max(.0001,a[i+1].time-a[i].time);return a[i].value+(a[i+1].value-a[i].value)*q}} return base};
      const kx=interp("x",l.x), ky=interp("y",l.y), ks=interp("scale",l.scale), kr=interp("rotation",l.rotation), ko=interp("opacity",l.opacity);
      const fade=Math.min(1,local/.4,(l.duration-local)/.4);
      const adj=l.colorAdjust||{brightness:0,contrast:1,saturation:1,blur:0};
      g.save(); g.translate((w-p.width*scale)/2,(h-p.height*scale)/2); g.scale(scale,scale);
      g.globalAlpha=Math.max(0,Math.min(1,ko*fade));
      g.globalCompositeOperation=l.blend==="Add"?"lighter":l.blend==="Screen"?"screen":l.blend==="Multiply"?"multiply":l.blend==="Darken"?"darken":"source-over";
      g.translate(kx,ky); g.rotate(kr*Math.PI/180); g.scale(ks,ks);
      if(l.kind==="text"){g.fillStyle=l.color||"#fff";g.font="900 86px Arial";g.textAlign="center";g.shadowBlur=16;g.shadowColor=l.color||"#fff";g.fillText(l.name,0,0)}
      else if(l.kind==="vfx")paintVfx(g,l.effect||"Fire",time,l.color);
      else if(m instanceof HTMLVideoElement && m.readyState>=2) g.drawImage(m,-p.width/2,-p.height/2,p.width,p.height);
      else if(m instanceof HTMLImageElement) g.drawImage(m,-p.width/2,-p.height/2,p.width,p.height);
      else if(l.kind==="shape"){g.fillStyle=l.color||"#fff";g.fillRect(-p.width/4,-p.height/4,p.width/2,p.height/2)}
      if(l.mask?.type!=="none"){g.restore();g.save();g.globalCompositeOperation="destination-in";g.filter=l.mask.feather?`blur(${Math.max(0,l.mask.feather)}px)`:"none";g.beginPath();if(l.mask.type==="circle")g.arc(w/2,h/2,Math.min(w,h)*.35,0,Math.PI*2);else if(l.mask.type==="split")g.rect(0,0,w/2,h);else g.rect(w*.1,h*.1,w*.8,h*.8);g.fill();g.restore();return}
      g.restore();
    },
    onProgress:v=>setNotice("Rendering "+Math.round(v*100)+"%")
  }).then(blob=>{const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="DIV-EDIT-project.mp4";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);setNotice("Project MP4 export finished")})
    .catch(err=>{console.error(err);setNotice("Project render failed — try again with a shorter timeline")});
 } function setRatio(v:string){const d:any={"9:16":[1080,1920],"16:9":[1920,1080],"1:1":[1080,1080],"4:5":[1080,1350]};if(d[v])commit({...p,width:d[v][0],height:d[v][1]});else{const w=Number(prompt("Custom width",String(p.width)));const h=Number(prompt("Custom height",String(p.height)));if(w>0&&h>0)commit({...p,width:w,height:h})}}
 function runFeature(num:number,name:string){setFeature(num);const low=name.toLowerCase();if(low.includes("split"))split();else if(low==="reverse"){if(sel&&sel.kind==="video")commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,effect:l.effect==="Reverse"?undefined:"Reverse"}:l)});setNotice("Reverse processing enabled")}else if(low.includes("freeze")){if(sel&&sel.kind==="video")commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,effect:"Freeze"}:l)});setNotice("Freeze-frame processing enabled")}else if(low.includes("duplicate")&&sel){const n={...sel,id:uid(),start:Math.min(p.duration,sel.start+sel.duration)};commit({...p,layers:[...p.layers,n],duration:Math.max(p.duration,n.start+n.duration)});setSelected(n.id)}else if(low.includes("delete")&&sel){commit({...p,layers:p.layers.filter(l=>l.id!==sel.id)});setSelected(null)}else if(low.includes("new project")){setP(fresh());setSelected(null)}else if(low.includes("add text"))add("text","DIV EDIT TEXT");else if(low.includes("vfx")||vfx.some(v=>low===v.toLowerCase()))add("vfx",name,undefined,name);else if(low.includes("ratio"))setRatio("9:16");else if(low.includes("marker"))setMarkers(m=>[...m,t]);else if(low.includes("beat")){setMarkers(Array.from({length:Math.max(1,Math.floor(p.duration/2))},(_,i)=>(i+1)*2).filter(x=>x<p.duration));setNotice("Beat markers generated locally")}else if(low.includes("speed")){if(sel)commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,speed:Math.min(100,Math.max(.1,l.speed===1?2:l.speed*2)),effect:"Speed Curve"}:l)});setNotice("Speed curve updated") }else if(low.includes("transition")){if(sel)commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,transition:{type:"fade",duration:.5}}:l)});setNotice("Fade transition enabled")}else if(low.includes("color")||low.includes("hsl")||low.includes("contrast")){if(sel)commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,colorAdjust:{...(l.colorAdjust||{brightness:0,contrast:1,saturation:1,blur:0}),contrast:1.12,saturation:1.08}}:l)});setNotice("Color processing enabled")}else if(low.includes("grid"))commit({...p,settings:{...p.settings,grid:!p.settings.grid}});else if(low.includes("safe"))commit({...p,settings:{...p.settings,safe:!p.settings.safe}});else setNotice(name+" panel opened — local editor control ready")}
 const visibleFeatures=features.filter(f=>!search||f[2].toLowerCase().includes(search.toLowerCase())||f[0].toLowerCase().includes(search.toLowerCase()));
 const currentModule=tab==="All"?null:tab;
 const moduleFeatures=currentModule?visibleFeatures.filter(f=>f[0]===currentModule):visibleFeatures;
 return <div className="app">
 {splash&&<div className="splash"><div className="splashLogo"><span className="tear">◢</span><b>DIV EDIT</b></div><span>POWERED BY DIVSTUDIO.NG</span></div>}
 <header className="topbar"><button onClick={()=>setScreen("home")}>‹</button><div className="brandWrap"><span className="brand">DIV EDIT</span><small>POWERED BY DIVSTUDIO.NG</small></div><div className="grow"/><button onClick={undo}><Undo2/></button><button onClick={redo}><Redo2/></button><button onClick={save}><Save/></button><label><Upload/> Import<input hidden multiple type="file" accept="video/*,image/*,audio/*" onChange={importFiles}/></label><button onClick={()=>document.documentElement.requestFullscreen()}><Maximize/></button><button className="export" onClick={exportVideo}><Download/> Export</button></header>
 <div className="workspace">
 {screen==="home"?<main className="home"><div className="homeBrand"><div className="homeLogo"><span className="tear">◢</span>DIV EDIT</div><small>POWERED BY DIVSTUDIO.NG</small></div><button className="newProject" onClick={()=>{setP(fresh());setSelected(null);setScreen("editor")}}><Plus/> NEW PROJECT</button><label className="homeImport"><Upload/> Import Media<input hidden multiple type="file" accept="video/*,image/*,audio/*" onChange={importFiles}/></label><section className="recent"><h2>Features</h2>{modules.map(m=><button className="moduleCard" key={m} onClick={()=>{setTab(m);setScreen("editor")}}>{React.createElement(moduleIcon[m],{size:20})}<div><b>{m}</b><small>{features.filter(f=>f[0]===m).length} features</small></div><span>›</span></button>)}</section></main>:<>
 <aside className="side capcutRail">{capcutTools.map(([label,I,action])=><button key={label} className={tab===action||tab===label?"active":""} onClick={()=>{setTab(action as string); if(action==="Edit"){setSearch("");} else {setSearch(action as string)}}}><I/><span>{label}</span></button>)}</aside>
 <main className="center">
  <div className="mediaAdd"><label className="addMedia"><Plus/><b>Add Media</b><span>Video • Photo • Audio</span><input hidden multiple type="file" accept="video/*,image/*,audio/*" onChange={importFiles}/></label></div>
  <div className="preview"><div className="canvasWrap"><canvas ref={canvas} width={540} height={960}/></div><div className="previewControls"><button onClick={()=>setPlaying(x=>!x)}>{playing?<Pause/>:<Play/>}</button><button onClick={()=>{setPlaying(false);setT(0)}}><Square/></button><input type="range" min="0" max={p.duration} step={1/p.fps} value={t} onChange={e=>setT(+e.target.value)}/><span>{t.toFixed(1)}s / {p.duration.toFixed(1)}s</span></div></div>
  <div className="featureBar"><div className="featureSearch"><Search size={15}/><input placeholder="Search features..." value={search} onChange={e=>setSearch(e.target.value)}/></div></div>
  <div className="bottomTools">{moduleFeatures.map(f=><div className="tool" key={f[1]}><button className={feature===f[1]?"active":""} onClick={()=>runFeature(f[1],f[2])}><Plus/><small>{String(f[1]).padStart(2,"0")}</small><span>{f[2]}</span></button></div>)}</div>
  <div className="timeline"><div className="timelineHead"><b>Timeline</b><span>{p.width}×{p.height}</span><span>{p.fps} FPS</span><span>{p.duration.toFixed(1)}s</span><span>Markers {markers.length}</span><span>{notice}</span></div>{p.layers.slice().reverse().map(l=><div className={"track "+(selected===l.id?"active":"")} key={l.id} onClick={()=>setSelected(l.id)}><div className="trackName"><Eye size={13}/><Lock size={13}/>{l.name}</div><div className="lane"><div className={"clip "+l.kind} style={{left:(l.start/p.duration)*100+"%",width:(l.duration/p.duration)*100+"%"}}>{l.name}</div></div></div>)}{!p.layers.length&&<div className="emptyTimeline">Import media or add a feature to start editing.</div>}</div>
 </main>
 <aside className="inspector"><h3>DIV EDIT • FEATURE ENGINE</h3>{sel?<><b>{sel.name}</b>{[["x","Position X",0,p.width],["y","Position Y",0,p.height],["scale","Scale",.1,4],["rotation","Rotation",-360,360],["opacity","Opacity",0,1],["speed","Speed",.1,100]].map(([k,n,min,max])=><label className="field" key={k}>{n}<input type="range" min={min} max={max} step={k==="opacity"?.01:.1} value={(sel as any)[k]} onChange={e=>setP(q=>({...q,layers:q.layers.map(l=>l.id===sel.id?{...l,[k]:+e.target.value}:l)}))}/></label>)}<select value={sel.blend} onChange={e=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,blend:e.target.value}:l)})}>{["Normal","Screen","Add","Lighten","Overlay","Soft Light","Multiply","Darken"].map(x=><option key={x}>{x}</option>)}</select><select value={sel.mask?.type||"none"} onChange={e=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,mask:{...(l.mask||{feather:0}),type:e.target.value as any}}:l)})}><option value="none">Mask: None</option><option value="circle">Circle Mask</option><option value="rectangle">Rectangle Mask</option><option value="line">Line Mask</option><option value="split">Split Mask</option><option value="custom">Custom Mask</option></select><label className="field">Mask Feather<input type="range" min="0" max="200" value={sel.mask?.feather||0} onChange={e=>setP(q=>({...q,layers:q.layers.map(l=>l.id===sel.id?{...l,mask:{type:l.mask?.type||"none",feather:+e.target.value}}:l)}))}/></label><div className="keyRow"><button onClick={()=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,keyframes:{...l.keyframes,x:[...(l.keyframes.x||[]),{time:t,value:l.x}],y:[...(l.keyframes.y||[]),{time:t,value:l.y}]}}:l)})}><KeyRound/> Position</button><button onClick={()=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,keyframes:{...l.keyframes,scale:[...(l.keyframes.scale||[]),{time:t,value:l.scale}],rotation:[...(l.keyframes.rotation||[]),{time:t,value:l.rotation}]}}:l)})}><KeyRound/> Transform</button><button onClick={()=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,keyframes:{...l.keyframes,opacity:[...(l.keyframes.opacity||[]),{time:t,value:l.opacity}]}}:l)})}><KeyRound/> Opacity</button></div><button onClick={split}><Scissors/> Split</button><button onClick={()=>{commit({...p,layers:p.layers.filter(l=>l.id!==sel.id)});setSelected(null)}}><Trash2/> Delete</button></>:<><p>Select a clip to adjust it.</p><div className="quickActions"><button onClick={()=>runFeature(5,"Magnetic snapping")}>Snap</button><button onClick={()=>runFeature(13,"Gridlines / safe zones")}>Grid</button><button onClick={()=>runFeature(10,"Freeze frame")}>Freeze</button><button onClick={()=>runFeature(9,"Reverse")}>Reverse</button></div></>}</aside>
 </>}
 </div>
 {p.layers.filter(l=>l.kind==="video"&&l.src).map(l=><video key={l.id} ref={v=>{vids.current[l.id]=v}} src={l.src} muted playsInline style={{display:"none"}}/>)}
 </div>
}
createRoot(document.getElementById("root")!).render(<App/>);