import React,{useEffect,useMemo,useRef,useState}from"react";import{createRoot}from"react-dom/client";import{Play,Pause,Square,Upload,Save,Undo2,Redo2,Scissors,Trash2,Sparkles,Layers,Download,Maximize,Plus,Eye,Lock,Music,Type,Sticker,SlidersHorizontal,Film,AudioLines,Blend,KeyRound,Mask,Move3d,Image as ImageIcon,RotateCcw}from"lucide-react";import"./styles.css";
type Kind="video"|"image"|"audio"|"text"|"vfx";type KF={time:number;value:number};type Layer={id:string;name:string;kind:Kind;src?:string;start:number;duration:number;visible:boolean;locked:boolean;x:number;y:number;scale:number;rotation:number;opacity:number;blend:string;effect?:string;keyframes:Record<string,KF[]>};type Project={name:string;width:number;height:number;fps:number;duration:number;layers:Layer[]};
const id=()=>crypto.randomUUID();const effects=["Fire","Fireball","Fire in Hand","Fire Trail","Fire Weapon","Fire Explosion","Embers","Sparks","Lightning","Electric Hand","Lightning Beam","Energy Ball","Energy Beam","Energy Blast","Energy Shield","Smoke","Fog","Dust","Magic Portal","Fire Portal","Lightning Portal","Magic Circle","Shockwave","Glow","Motion Trail","Camera Shake"];
const tools=[["Edit",Scissors],["Audio",Music],["Text",Type],["Stickers",Sticker],["Effects",Sparkles],["Magic",Sparkles],["Overlay",Layers],["Filters",Film],["Adjust",SlidersHorizontal],["Transitions",Blend],["Masks",Mask],["Keyframe",KeyRound],["Tracking",Move3d]];
const fresh=():Project=>({name:"New Project",width:1080,height:1920,fps:30,duration:10,layers:[]});
function App(){const[p,setP]=useState(fresh);const[selected,setSelected]=useState<string|null>(null);const[t,setT]=useState(0);const[playing,setPlaying]=useState(false);const[tab,setTab]=useState("Edit");const[history,setHistory]=useState<Project[]>([]);const[future,setFuture]=useState<Project[]>([]);const[zoom,setZoom]=useState(1);const canvas=useRef<HTMLCanvasElement>(null);const vids=useRef<Record<string,HTMLVideoElement|null>>({});const sel=p.layers.find(x=>x.id===selected);
const commit=(n:Project)=>{setHistory(h=>[...h,p].slice(-50));setFuture([]);setP(n)};
useEffect(()=>{if(!playing)return;let f:number;const tick=()=>{setT(x=>{const n=x+1/p.fps;if(n>=p.duration){setPlaying(false);return 0}return n});f=requestAnimationFrame(tick)};f=requestAnimationFrame(tick);return()=>cancelAnimationFrame(f)},[playing,p.fps,p.duration]);
useEffect(()=>draw(),[p,t,selected]);
function draw(){const c=canvas.current;if(!c)return;const x=c.getContext("2d");if(!x)return;x.clearRect(0,0,c.width,c.height);x.fillStyle="#050505";x.fillRect(0,0,c.width,c.height);const s=Math.min(c.width/p.width,c.height/p.height);x.save();x.translate((c.width-p.width*s)/2,(c.height-p.height*s)/2);x.scale(s,s);p.layers.filter(l=>l.visible&&t>=l.start&&t<=l.start+l.duration).forEach(l=>{x.save();x.globalAlpha=l.opacity;x.globalCompositeOperation=l.blend==="Add"?"lighter":l.blend==="Screen"?"screen":l.blend==="Multiply"?"multiply":"source-over";x.translate(l.x,l.y);x.rotate(l.rotation*Math.PI/180);x.scale(l.scale,l.scale);if(l.kind==="text"){x.fillStyle="#fff";x.font="bold 80px Arial";x.textAlign="center";x.shadowBlur=18;x.shadowColor="#fff";x.fillText(l.name,0,0)}else if(l.kind==="vfx")effect(x,l.effect||"Fire",t);else{const v=vids.current[l.id];if(v&&v.readyState>=2)x.drawImage(v,-p.width/2,-p.height/2,p.width,p.height)}x.restore()});x.restore()}
function effect(x:CanvasRenderingContext2D,e:string,t:number){const q=.8+.2*Math.sin(t*8);x.save();if(e.includes("Lightning")){x.strokeStyle="#b9ecff";x.lineWidth=16;x.shadowBlur=35;x.shadowColor="#5ad8ff";x.beginPath();for(let i=0;i<10;i++)x.lineTo((i-5)*55,(i%2?80:-80)*q);x.stroke()}else if(e.includes("Circle")||e.includes("Portal")){x.strokeStyle="#8de8ff";x.lineWidth=12;x.shadowBlur=30;x.shadowColor="#43cfff";for(let r=220;r>30;r-=38){x.beginPath();x.arc(0,0,r,0,Math.PI*2);x.stroke()}}else{const g=x.createRadialGradient(0,0,5,0,0,240);g.addColorStop(0,"#fff");g.addColorStop(.2,"#ffe56e");g.addColorStop(.55,"#ff6420");g.addColorStop(1,"transparent");x.fillStyle=g;x.shadowBlur=55;x.shadowColor="#ff5a16";x.beginPath();x.arc(0,0,230*q,0,Math.PI*2);x.fill()}x.restore()}
function add(kind:Kind,name:string,src?:string){const l:Layer={id:id(),name,kind,src,start:t,duration:3,visible:true,locked:false,x:p.width/2,y:p.height/2,scale:1,rotation:0,opacity:1,blend:kind==="vfx"?"Add":"Normal",keyframes:{}};commit({...p,layers:[...p.layers,l],duration:Math.max(p.duration,t+3)});setSelected(l.id)}
function importFiles(e:React.ChangeEvent<HTMLInputElement>){Array.from(e.target.files||[]).forEach(f=>add(f.type.startsWith("audio")?"audio":f.type.startsWith("image")?"image":"video",f.name,URL.createObjectURL(f)));e.target.value=""}
function split(){if(!sel)return;const a=t-sel.start;if(a<=0||a>=sel.duration)return;commit({...p,layers:p.layers.flatMap(l=>l.id===sel.id?[{...l,duration:a},{...l,id:id(),start:t,duration:l.duration-a}]:[l])})}
function undo(){if(!history.length)return;setFuture(f=>[p,...f]);setP(history.at(-1)!);setHistory(h=>h.slice(0,-1))}
function redo(){if(!future.length)return;setHistory(h=>[...h,p]);setP(future[0]);setFuture(f=>f.slice(1))}
function save(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:"application/json"}));a.download="div-edit-project.json";a.click()}
function exportVideo(){const c=canvas.current;if(!c)return;const r=new MediaRecorder(c.captureStream(p.fps),{mimeType:"video/webm"});const chunks:Blob[]=[];r.ondataavailable=e=>chunks.push(e.data);r.onstop=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(chunks,{type:"video/webm"}));a.download="div-edit.webm";a.click()};setT(0);setPlaying(true);r.start();setTimeout(()=>{r.stop();setPlaying(false)},p.duration*1000+300)}
const options=useMemo(()=>{if(tab==="Magic")return effects;if(tab==="Text")return["Add Text","Fade","Slide","Zoom","Typewriter","Bounce","Shake"];if(tab==="Audio")return["Music","Sound Effects","Volume","Fade In","Fade Out"];if(tab==="Effects")return["Glow","Motion Blur","Camera Shake","Flash","Ripple","Warp","Radial Blur","Chromatic Aberration"];if(tab==="Transitions")return["Fade","Dissolve","Flash","Zoom","Spin","Glitch","Blur","Light Burst","Portal","Magic"];if(tab==="Masks")return["Rectangle","Circle","Polygon","Free Draw"];if(tab==="Keyframe")return["Position","Scale","Rotation","Opacity","Blur","Glow","Intensity"];return["Split","Delete","Duplicate","Freeze","Reverse","Rotate","Crop","Speed"]},[tab]);
function action(v:string){if(v==="Import Media")document.querySelector<HTMLInputElement>('input[type=file]')?.click();else if(v==="Add Text")add("text","MAGIC TEXT");else if(effects.includes(v))add("vfx",v);else if(v==="Split")split();else if(v==="Delete"&&selected){commit({...p,layers:p.layers.filter(l=>l.id!==selected)});setSelected(null)}}
return <div className="app">
<header className="topbar"><button onClick={()=>setP(fresh())}>‹</button><span className="brand">DIV EDIT</span><span className="desktopOnly">{p.name}</span><div className="grow"/><button onClick={undo}><Undo2/></button><button onClick={redo}><Redo2/></button><button className="desktopOnly" onClick={save}><Save/></button><label className="desktopOnly"><Upload/> Import<input hidden multiple type="file" accept="video/*,image/*,audio/*" onChange={importFiles}/></label><button onClick={()=>document.documentElement.requestFullscreen()}><Maximize/></button><button className="export" onClick={exportVideo}>Export</button></header>
<div className="workspace">
<aside className="side">{tools.map(([n,I])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n as string)}><I/><span>{n}</span></button>)}</aside>
<main className="center"><div className="preview"><div className="canvasWrap"><canvas ref={canvas} width={540} height={960}/></div><div className="previewControls"><button onClick={()=>setPlaying(x=>!x)}>{playing?<Pause/>:<Play/>}</button><button onClick={()=>{setPlaying(false);setT(0)}}><Square/></button><button onClick={()=>setT(x=>Math.max(0,x-1/p.fps))}>‹</button><input type="range" min="0" max={p.duration} step={1/p.fps} value={t} onChange={e=>setT(+e.target.value)}/><span>{t.toFixed(1)}s</span><button onClick={()=>setT(x=>Math.min(p.duration,x+1/p.fps))}>›</button></div></div>
<div className="bottomTools">{options.map(v=><div className="tool" key={v}><button onClick={()=>action(v)}><Plus/>{v}</button></div>)}</div>
<div className="timeline"><div className="timelineHead"><b>Timeline</b><span>9:16</span><span>{p.fps} FPS</span><span>{p.duration.toFixed(1)}s</span><input type="range" min=".5" max="3" step=".1" value={zoom} onChange={e=>setZoom(+e.target.value)}/></div>{p.layers.slice().reverse().map(l=><div className={"track "+(selected===l.id?"active":"")} key={l.id} onClick={()=>setSelected(l.id)}><div className="trackName"><Eye size={13}/><Lock size={13}/>{l.name}</div><div className="lane"><div className={"clip "+l.kind} style={{left:(l.start/p.duration)*100*zoom+"%",width:(l.duration/p.duration)*100*zoom+"%"}}>{l.name}</div></div></div>)}</div></main>
<aside className="inspector"><h3>ADJUST</h3>{sel?<><b>{sel.name}</b>{[["x","Position X",0,1080],["y","Position Y",0,1920],["scale","Scale",.1,4],["rotation","Rotation",-360,360],["opacity","Opacity",0,1]].map(([k,n,min,max])=><label className="field" key={k}>{n}<input type="range" min={min} max={max} step={k==="opacity"?.01:.1} value={(sel as any)[k]} onChange={e=>{const v=+e.target.value;setP(q=>({...q,layers:q.layers.map(l=>l.id===sel.id?{...l,[k]:v}:l)}))}}/></label>)}<select value={sel.blend} onChange={e=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,blend:e.target.value}:l)})}>{["Normal","Screen","Add","Lighten","Overlay","Soft Light","Multiply","Darken","Color Dodge"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>commit({...p,layers:p.layers.map(l=>l.id===sel.id?{...l,keyframes:{...l.keyframes,opacity:[...(l.keyframes.opacity||[]),{time:t,value:l.opacity}]}}:l)})}><KeyRound/> Add Keyframe</button><button onClick={split}><Scissors/> Split</button><button onClick={()=>{commit({...p,layers:p.layers.filter(l=>l.id!==sel.id)});setSelected(null)}}><Trash2/> Delete</button></>:<p>Select a clip to edit.</p>}</aside></div>
{p.layers.filter(l=>l.kind==="video"&&l.src).map(l=><video key={l.id} ref={v=>{vids.current[l.id]=v}} src={l.src} muted playsInline style={{display:"none"}}/>)}
</div>}
createRoot(document.getElementById("root")!).render(<App/>);